# Generated by Django 2.2 on 2021-03-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20210318_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_name',
            new_name='singer_name',
        ),
    ]
