# Generated by Django 2.2 on 2021-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20210318_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('paying', '待支付'), ('cancel', '取消'), ('success', '成功')], default='paying', max_length=30, null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(default='', max_length=200, verbose_name='订单留言'),
        ),
    ]
