# Generated by Django 2.2 on 2021-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20210318_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='订单留言'),
        ),
    ]
