# Generated by Django 2.2 on 2021-03-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20210321_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('TRADE_FINISHED', '交易结束'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '超时关闭'), ('paying', '待支付'), ('TRADE_SUCCESS', '成功')], default='paying', max_length=30, null=True, verbose_name='订单状态'),
        ),
    ]
