# Generated by Django 2.2 on 2021-03-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20210322_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '超时关闭'), ('paying', '待支付'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束')], default='paying', max_length=30, null=True, verbose_name='订单状态'),
        ),
    ]
