# Generated by Django 2.2 on 2021-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_auto_20210322_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付'), ('WAIT_BUYER_PAY', '交易创建')], default='paying', max_length=30, null=True, verbose_name='订单状态'),
        ),
    ]
