# Generated by Django 2.2 on 2021-03-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_auto_20201024_1537'),
        ('trade', '0018_auto_20210322_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('WAIT_BUYER_PAY', '交易创建'), ('paying', '待支付'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束')], default='paying', max_length=30, null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='订单留言'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'goods')},
        ),
    ]
