# Generated by Django 2.2 on 2021-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_auto_20210322_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('WAIT_BUYER_PAY', '交易创建'), ('paying', '待支付'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束'), ('TRADE_CLOSED', '超时关闭')], default='paying', max_length=30, null=True, verbose_name='订单状态'),
        ),
    ]
